on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        groovy: [2.5.14, 3.0.8]
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - run: ./gradlew groovydoc -P groovy=${{ matrix.groovy }}
      - uses: actions/upload-artifact@v2
        with:
          name: groovydoc build by Groovy ${{ matrix.groovy }}
          path: build/docs/groovydoc
